/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jiangchuanfa_javacallcaandccalljava_Call */

#ifndef _Included_com_example_jiangchuanfa_javacallcaandccalljava_Call
#define _Included_com_example_jiangchuanfa_javacallcaandccalljava_Call
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jiangchuanfa_javacallcaandccalljava_Call
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_jiangchuanfa_javacallcaandccalljava_Call_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_jiangchuanfa_javacallcaandccalljava_Call
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jiangchuanfa_javacallcaandccalljava_Call_callbackAdd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
